create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  rating int not null check (rating between 1 and 5),
  quote text not null,
  byline text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

create policy "Reviews are readable"
on public.reviews
for select
to anon
using (true);

create policy "Anyone can submit reviews"
on public.reviews
for insert
to anon
with check (true);
